apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: rhdh-okta
  namespace: rh-sso
  finalizers:
    - realm.cleanup
  labels:
    app: backstage
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Okta Authentication Realm
    enabled: true
    id: rhdh
    identityProviders:
      - enabled: true
        config:
          clientId: <<CLIENT ID FROM BITBUCKET OAUTH CONSUMER>>
          clientSecret: <<CLIENT SECRET FROM BITBUCKET OAUTH CONSUMER>>
          syncMode: IMPORT
          useJwksUrl: 'true'
        firstBrokerLoginFlowAlias: first broker login
        trustEmail: false
        linkOnly: false
        providerId: bitbucket
        alias: bitbucket
        addReadTokenRoleOnCreate: false
        storeToken: false
    realm: backstage
status:
  loginURL: ''
  message: ''
  phase: reconciling
  ready: true
