apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: rhdh-okta
  namespace: rh-sso
  finalizers:
    - realm.cleanup
  labels:
    app: backstage
spec:
  instanceSelector:
    matchLabels:
      app: sso
  realm:
    displayName: Okta Authentication Realm
    enabled: true
    id: rhdh
    realm: backstage
status:
  loginURL: ''
  message: ''
  phase: reconciling
  ready: true
